website/__init__.py
from flask import Flask
#from flask_sqlalchemy import SQLAlchemy
#from flask_bcrypt import Bcrypt

#Everything that's commented out is related to the current lack of need for a db and users

#db = SQLAlchemy()
#bcrypt = Bcrypt()
#login_manager = LoginManager()
#login_manager.login_view = 'users.login'
#login_manager.login_message_category = 'info'

#def create_app(config_class=Config):
def create_app():
    app = Flask(__name__)
#    app.config.from_object(Config)

#    db.init_app(app)
#    bcrypt.init_app(app)
#    login_manager.init_app(app)

    from website.users.routes import users
    from website.classes.routes import classes
    from website.main.routes import main
    app.register_blueprint(classes)
    app.register_blueprint(users)
    app.register_blueprint(main)

    return app

website/classes/routes.py
from flask import Blueprint

classes = Blueprint('classes', __name__)

website/main/routes.py
from flask import Blueprint, render_template, request, redirect
  
main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    return (render_template('index.html',title='Steam Bot Workshop'))

@main.route("/callback")
def callback():
    return redirect(url_for('home.home'))

website/users/routes.py
from flask import Blueprint

users = Blueprint('users', __name__)

website/templates/index.html
{% extends "layout.html" %}
{% block content %}
 <div>
  <h3 class = "container"> Hello </h3>
 </div>
  {% endblock content %}

website/templates/layout.html
<!DOCTYPE html>
<html lang = "en">
<head>
 <title>Steambot Workshop</title>
 <meta charset = "utf-8">
 <!-- <link rel="icon" type="image/png" href="{{url_for('static', filename='STEAM-bot-head.png')}}"> -->
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
 <nav class = "navbar fixed-top">
  <a class="navbar-brand" href="{{url_for('main.home')}}">
   <img src="{{url_for('static', filename='STEAM-bot-head.png')}}" alt="Steam Bot Workshop Logo">
  </a>
 </nav>
 <main class = "container">
  {% with messages=get_flashed_messages(with_categories=true) %}
   {% if messages %}
    {% for category, message in messages %}
     <div class="alert alert-{{category}}">
      {{ message }}
     </div>
    {% endfor %}
   {% endif %}
  {% endwith %}
  {%block content%} {%endblock%}
 </main>
 <div class = "page-footer text-center">
  @2019, International Tech Academics. <a href="mailto:Robert@intltechacademics.com">Contact</a>
 </div>
</body>
</html> 